/**
 * Shared formatting for the Instrument (home redesign) — sign conventions,
 * tabular dates, and en-CA money are part of the design, so every module
 * pulls from here instead of hand-rolling.
 *
 * Conventions (from the handoff):
 *   - Real minus sign (U+2212), never a hyphen: "−0.48%"
 *   - Explicit plus on positives: "+0.43%"
 *   - Direction is never color-only — pair red with ▲/▼ or a label
 *   - Dates as "TUESDAY 30.06.2026" / chips as "JUN 30, 2025"
 *   - Money en-CA, no decimals at poster scale: "$22,690"
 */

export const MINUS = "−";
export const UP = "▲"; // ▲
export const DOWN = "▼"; // ▼

/** "+0.43%" / "−0.48%" — signed percent with a true minus. */
export function fmtSignedPct(value: number, decimals = 2): string {
  const sign = value < 0 ? MINUS : "+";
  return `${sign}${Math.abs(value).toFixed(decimals)}%`;
}

/** "+0.30 PP" / "−0.03 PP" — contribution in percentage points. */
export function fmtSignedPp(value: number, decimals = 2): string {
  const sign = value < 0 ? MINUS : "+";
  return `${sign}${Math.abs(value).toFixed(decimals)} PP`;
}

/** "±0.39%" — symmetric typical-day move. */
export function fmtPlusMinusPct(value: number, decimals = 2): string {
  return `±${Math.abs(value).toFixed(decimals)}%`;
}

/** "51.87" — price tape, always two decimals, no currency symbol. */
export function fmtPrice(value: number): string {
  return value.toFixed(2);
}

/** "$22,690" — en-CA money, rounded to whole dollars. */
export function fmtMoney(value: number): string {
  return new Intl.NumberFormat("en-CA", {
    style: "currency",
    currency: "CAD",
    maximumFractionDigits: 0,
  }).format(Math.round(value));
}

/** "1,868" — grouped integer (day №, session counts). */
export function fmtInt(value: number): string {
  return new Intl.NumberFormat("en-CA", {
    maximumFractionDigits: 0,
  }).format(value);
}

/** "TUESDAY 30.06.2026" — the dateline stamp. */
export function fmtDateline(date: Date): string {
  const weekday = date
    .toLocaleDateString("en-CA", { weekday: "long" })
    .toUpperCase();
  const dd = String(date.getDate()).padStart(2, "0");
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  return `${weekday} ${dd}.${mm}.${date.getFullYear()}`;
}

/** "JUN 30, 2025" — what-if date chips. */
export function fmtChipDate(date: Date): string {
  return date
    .toLocaleDateString("en-CA", {
      month: "short",
      day: "numeric",
      year: "numeric",
    })
    .toUpperCase();
}

/** "JUN 30" — short readout dates (session board). */
export function fmtShortDate(date: Date): string {
  return date
    .toLocaleDateString("en-CA", { month: "short", day: "numeric" })
    .toUpperCase();
}

/** "MON" — week-strip day letters. */
export function fmtWeekday(date: Date): string {
  return date
    .toLocaleDateString("en-CA", { weekday: "short" })
    .toUpperCase();
}

/**
 * Parse an API "YYYY-MM-DD" date at noon UTC so the local calendar day
 * never slips a day in western time zones.
 */
export function parseSessionDate(iso: string): Date {
  return new Date(`${iso.slice(0, 10)}T12:00:00Z`);
}

/* ── The session-board heat function ───────────────────────────────────────
 * Lives here rather than in either board because there are TWO boards —
 * components/home/HeatmapCard (the 90D card) and
 * components/inside/InsideHeatBoard (the deep board on /inside-veqt) — and
 * they are the same instrument read at two zoom levels. They were verbatim
 * copies of each other and had already drifted once: the accessibility floor
 * below landed on the home card alone, so for one release the same session
 * printed two different reds. One function, two call sites; the legend
 * gradients in each sheet are CSS literals that must be regenerated by hand
 * from THIS function whenever it changes (interpolating them would make both
 * styled-jsx sheets dynamic, and the boards re-render on every hover).
 * ──────────────────────────────────────────────────────────────────────── */

/** Below this |pct| the day is "flat" — no direction, no colour, no hatch. */
export const FLAT_BAND = 0.03;

/** A cell that carries a down move — i.e. gets red, and gets hatched. */
export function isDownCell(pct: number): boolean {
  return pct <= -FLAT_BAND;
}

/**
 * Handoff heat function — literal colors by spec (stays fixed under editions).
 *
 * DOWN CELLS GET A DARKER FLOOR (accessibility pass, build contract §7).
 *
 *   up   a = min(0.92, 0.10 + (|pct| / 1.4) * 0.82)   ← unchanged
 *   down a = min(0.92, 0.20 + (|pct| / 1.4) * 0.72)   ← floor 0.10 → 0.20
 *
 * Why: red-blind viewers read hue as lightness, so the board's direction
 * has to survive in the value channel alone. It did not at the quiet end.
 * Composited on paper, a 0.1% down day used to land at rgb(251,225,222)
 * — luminance 0.797 against the flat-day gray's 0.897, a contrast ratio of
 * 1.12. Effectively "nothing happened". With the floor it lands at
 * rgb(249,208,203), luminance 0.697, ratio 1.27 — the quiet down days are
 * now visibly marked rather than merely tinted.
 *
 * The two ramps pivot about the SAME endpoint: 0.20 + 0.72 = 0.92 = the up
 * ramp's cap, reached at |pct| = 1.4 in both. So the floor rises, the top
 * of the ramp is bit-identical to before, and nothing can crush to a
 * black-red at the extremes (a 2% down is still rgb(234,83,63)).
 *
 * Known limit, deliberately accepted: alpha alone cannot carry direction.
 * Ink darkens to luminance 0.018 at the cap while red bottoms out at 0.240,
 * so an up cell is always the darker of a large-move pair no matter what
 * floor we choose — raising the down floor only moves the crossing point
 * where the two ramps read as the same value. This floor (0.20) puts that
 * crossing at |pct| = 0.094%, i.e. inside the near-flat band where the
 * cells are pale and direction carries no editorial weight. A heavier
 * floor (the 0.28 first sketched) pushes the crossing out to 0.25%, which
 * is the modal daily move for this fund — the worst possible place for it.
 * Direction is made shape-coded by the HATCH toggle both boards carry; this
 * function only guarantees a down day never reads as a flat day.
 */
export function heatColor(pct: number): string {
  if (Math.abs(pct) < FLAT_BAND) return "rgba(17,17,17,0.05)";
  const mag = Math.abs(pct) / 1.4;
  if (pct >= 0) {
    return `rgba(17,17,17,${Math.min(0.92, 0.1 + mag * 0.82).toFixed(2)})`;
  }
  return `rgba(232,68,46,${Math.min(0.92, 0.2 + mag * 0.72).toFixed(2)})`;
}

/** Persisted hatch preference — SHARED by both boards, so the reader's
 *  choice follows them from the home card to the deep board and back.
 *  Shares lib/cache's "buyveqt:" namespace. */
export const HATCH_KEY = "buyveqt:board-hatch";
