"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useVeqtData } from "@/lib/useVeqtData";
import type { HistoricalDataPoint } from "@/lib/types";
import {
  UP,
  DOWN,
  HATCH_KEY,
  fmtSignedPct,
  fmtChipDate,
  heatColor,
  isDownCell,
  parseSessionDate,
} from "@/lib/instrument-format";
import { useArmOnView } from "./useArmOnView";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const RANGES = ["90D", "1Y", "ALL"] as const;
type BoardRange = (typeof RANGES)[number];

const DAY_MS = 86_400_000;
const WEEK_MS = 7 * DAY_MS;
const YEAR_SESSIONS = 252;

const WEEKDAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] as const;
const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
] as const;

/** White gap + ink ring — the pinned/today cell marker. */
const PIN_RING = "0 0 0 1.5px #ffffff, 0 0 0 3px #111111";

/* ── Fill sweep ──────────────────────────────────────────────────────────
 * Cells fill oldest → today at ~2ms apart. 90D is 90 cells (180ms of
 * stagger) and 1Y is 252 (~500ms), but ALL runs to ~1,900 sessions, which at
 * a flat 2ms would drag the sweep out to ~3.8s. So the TOTAL stagger is
 * capped and the per-cell step shrinks to fit — a long range reads as a
 * faster wipe rather than a slower page.
 */
const CELL_STEP_MS = 2;
const SWEEP_CAP_MS = 1500;
/** The ringed cell lands last, a beat after the final cell of the sweep. */
const RING_BEAT_MS = 180;

interface DayCell {
  date: string;
  pct: number;
  /** 1-based grid column (calendar week) */
  col: number;
  /** 1-based grid row (Mon=1 … Fri=5) */
  row: number;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sliceStart(history: HistoricalDataPoint[], range: BoardRange): number {
  if (range === "90D") return Math.max(0, history.length - 90);
  if (range === "1Y") return Math.max(0, history.length - YEAR_SESSIONS);
  return 0;
}

/** Timestamp of the Monday of the week containing d. */
function mondayOf(d: Date): number {
  const back = (d.getUTCDay() + 6) % 7; // Mon=0 … Sun=6
  return d.getTime() - back * DAY_MS;
}

/* The heat ramp, the flat band, the down-cell test and the hatch preference
   key all live in lib/instrument-format.ts. This board used to carry its own
   copy of the ramp, which is exactly how it missed the down-cell accessibility
   floor that landed on the home card — for one release the same session
   printed two different reds on two pages. The legend gradient in the sheet
   below is a hand-written CSS literal that reads that function out; it has to
   be regenerated by hand if the ramp ever changes. */

/** "Mon Jun 29 — down 0.4%" — a11y label + native title. */
function cellLabel(iso: string, pct: number): string {
  const d = parseSessionDate(iso);
  const dir = pct > 0 ? "up" : pct < 0 ? "down" : "flat";
  return `${WEEKDAYS[d.getUTCDay()]} ${MONTHS[d.getUTCMonth()]} ${d.getUTCDate()} — ${dir} ${Math.abs(pct).toFixed(1)}%`;
}

// ---------------------------------------------------------------------------
// Component — "The year on tape."
// ---------------------------------------------------------------------------

/**
 * The deep session board (artboard 6a).
 *
 * Range tabs (90D / 1Y / ALL, 1Y default) · a four-cell facts strip
 * (sessions / up days / best / worst, worst in signal red) · the heat grid
 * with calendar weeks as columns and Mon–Fri as rows.
 *
 * Integration points preserved from the previous board:
 *   - `id="heatmap"` anchor, so `/inside-veqt#heatmap` lands here.
 *   - `?date=YYYY-MM-DD` pins that session in the readout and rings its cell;
 *     the range auto-promotes to ALL when the linked day predates the window.
 *   - Clicking a cell rewrites `?date=` (replace, no scroll) so every session
 *     is a shareable URL — the same contract the home card links into.
 */
export default function InsideHeatBoard() {
  const { data, loading } = useVeqtData("ALL");
  const router = useRouter();
  const pathname = usePathname();
  const params = useSearchParams();
  const dateParam = params.get("date");

  // `null` means "nobody has picked a tab yet", so the deep link still gets
  // to choose the window. Once the reader picks, their choice sticks.
  const [pickedRange, setPickedRange] = useState<BoardRange | null>(null);
  const [hover, setHover] = useState<number | null>(null);
  const [hatch, setHatch] = useState(false);
  const anchorRef = useRef<HTMLDivElement>(null);
  const scrolledRef = useRef(false);

  /* Hatch preference — the SAME storage key the home card writes, so the
     reader's direction setting follows them from the home board to this one
     and back. SSR-safe by construction: server and first client render both
     paint `false`, so hydration matches, and the stored value is applied on
     the pass after mount. Reading localStorage during render (or from a
     useState initialiser) would make the two disagree. The try/catch is not
     defensive padding — Safari private mode and blocked-cookie settings throw
     on access, the same case lib/cache.ts guards. */
  useEffect(() => {
    try {
      if (window.localStorage.getItem(HATCH_KEY) === "1") setHatch(true);
    } catch {
      /* storage unavailable — the default (off) stands */
    }
  }, []);

  const toggleHatch = () => {
    const next = !hatch;
    setHatch(next);
    try {
      window.localStorage.setItem(HATCH_KEY, next ? "1" : "0");
    } catch {
      /* storage unavailable — the toggle still works for this session */
    }
  };

  const history = useMemo<HistoricalDataPoint[]>(
    () => data?.historical ?? [],
    [data]
  );

  // A deep-linked day older than the default 1Y window would otherwise land
  // off the board — widen to ALL. Derived, not an effect, so there is no
  // second render pass.
  const defaultRange = useMemo<BoardRange>(() => {
    if (!dateParam || history.length === 0) return "1Y";
    const windowStart = history[Math.max(0, history.length - YEAR_SESSIONS)].date;
    return dateParam < windowStart ? "ALL" : "1Y";
  }, [dateParam, history]);

  const range = pickedRange ?? defaultRange;

  // `#heatmap` landing — scroll once the board actually has content, so the
  // anchor isn't chasing a collapsed section on first paint.
  useEffect(() => {
    if (scrolledRef.current) return;
    if (typeof window === "undefined") return;
    if (window.location.hash !== "#heatmap") return;
    if (history.length === 0) return;
    scrolledRef.current = true;
    anchorRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
  }, [history]);

  // Clicking a cell updates ?date= so the pin follows selection and each cell
  // is a shareable URL. Replace (not push) so we don't pollute history;
  // scroll:false because the board is already in view.
  const handleCellClick = useCallback(
    (date: string) => {
      const sp = new URLSearchParams(window.location.search);
      sp.set("date", date);
      router.replace(`${pathname}?${sp.toString()}#heatmap`, { scroll: false });
    },
    [pathname, router]
  );

  const cells = useMemo<DayCell[]>(() => {
    if (history.length === 0) return [];
    const start = sliceStart(history, range);
    const firstMonday = mondayOf(parseSessionDate(history[start].date));
    const out: DayCell[] = [];
    for (let i = start; i < history.length; i++) {
      const close = history[i].close;
      const prev = i > 0 ? history[i - 1].close : close;
      const pct = prev > 0 ? ((close - prev) / prev) * 100 : 0;
      const d = parseSessionDate(history[i].date);
      const row = Math.min(Math.max(d.getUTCDay(), 1), 5); // clamp to Mon–Fri
      const col = Math.round((mondayOf(d) - firstMonday) / WEEK_MS) + 1;
      out.push({ date: history[i].date, pct, col, row });
    }
    return out;
  }, [history, range]);

  const stats = useMemo(() => {
    let up = 0;
    let best: DayCell | null = null;
    let worst: DayCell | null = null;
    for (const c of cells) {
      if (c.pct > 0) up++;
      if (best === null || c.pct > best.pct) best = c;
      if (worst === null || c.pct < worst.pct) worst = c;
    }
    return { total: cells.length, up, best, worst };
  }, [cells]);

  // Pinned cell: the ?date= day when it's on the board, otherwise the last
  // session. Hover wins for the readout but never moves the ring.
  const pinnedIdx = useMemo(() => {
    if (dateParam) {
      const i = cells.findIndex((c) => c.date === dateParam);
      if (i >= 0) return i;
    }
    return cells.length - 1;
  }, [cells, dateParam]);

  const readIdx = hover ?? pinnedIdx;
  const readCell = readIdx >= 0 ? cells[readIdx] ?? null : null;
  const readPinned = hover === null && dateParam != null && pinnedIdx >= 0;
  const readNegative = (readCell?.pct ?? 0) < 0;

  const sessionsSub =
    range === "ALL"
      ? "SINCE INCEPTION"
      : range === "1Y"
        ? "LAST TRADING YEAR"
        : "LAST 90 SESSIONS";

  const showSkeleton = loading || cells.length === 0;

  // Arm the fill on the grid itself, not the section — the board is tall, and
  // observing the section would spend the sweep while the reader is still on
  // the facts strip. `ready` holds the observer back until the grid exists.
  const { ref: gridRef, armed } = useArmOnView<HTMLDivElement>(!showSkeleton);

  const sweep = useMemo(() => {
    const n = cells.length;
    const stepMs = n > 0 ? Math.min(CELL_STEP_MS, SWEEP_CAP_MS / n) : CELL_STEP_MS;
    return { stepMs, ringMs: Math.max(0, n - 1) * stepMs + RING_BEAT_MS };
  }, [cells.length]);

  return (
    <section className="tape" aria-label="The year on tape">
      <div ref={anchorRef} id="heatmap" className="tape__anchor" />

      <div className="tape__head">
        <div>
          <div className="tape__kicker">Sessions on file</div>
          <h2 className="tape__display">The year on tape.</h2>
        </div>
        <div className="tape__tabs" role="tablist" aria-label="Session range">
          {RANGES.map((r) => (
            <button
              key={r}
              type="button"
              role="tab"
              aria-selected={r === range}
              className={`tape__tab${r === range ? " is-active" : ""}`}
              onClick={() => {
                setPickedRange(r);
                setHover(null);
              }}
            >
              {r}
            </button>
          ))}
        </div>
      </div>

      <div className="tape__stats">
        <div className="tape__stat">
          <div className="tape__stat-label">Sessions</div>
          <div className="tape__stat-value">
            {stats.total > 0 ? stats.total : "—"}
          </div>
          <div className="tape__stat-sub">
            {stats.total > 0 ? sessionsSub : "—"}
          </div>
        </div>
        <div className="tape__stat">
          <div className="tape__stat-label">Up days</div>
          <div className="tape__stat-value">
            {stats.total > 0 ? stats.up : "—"}
          </div>
          <div className="tape__stat-sub">
            {stats.total > 0
              ? `${Math.round((stats.up / stats.total) * 100)}% of sessions`
              : "—"}
          </div>
        </div>
        <div className="tape__stat">
          <div className="tape__stat-label">Best day</div>
          <div className="tape__stat-value">
            {stats.best ? fmtSignedPct(stats.best.pct) : "—"}
          </div>
          <div className="tape__stat-sub">
            {stats.best ? fmtChipDate(parseSessionDate(stats.best.date)) : "—"}
          </div>
        </div>
        <div className="tape__stat">
          <div className="tape__stat-label">Worst day</div>
          <div className="tape__stat-value is-signal">
            {stats.worst ? fmtSignedPct(stats.worst.pct) : "—"}
          </div>
          <div className="tape__stat-sub">
            {stats.worst ? fmtChipDate(parseSessionDate(stats.worst.date)) : "—"}
          </div>
        </div>
      </div>

      {readCell && (
        <div className="tape__readout">
          <span className="tape__read-left">
            {hover !== null ? "Selected" : readPinned ? "Pinned" : "Latest"} ·{" "}
            <span className="tape__read-date">
              {fmtChipDate(parseSessionDate(readCell.date))}
            </span>
          </span>
          <span className={`tape__read-pct${readNegative ? " is-neg" : ""}`}>
            {readNegative ? DOWN : UP} {fmtSignedPct(readCell.pct)}
          </span>
        </div>
      )}

      {showSkeleton ? (
        <div className="tape__skeleton" aria-hidden />
      ) : (
        <div
          className="tape__scroll"
          ref={gridRef}
          data-armed={armed ? "true" : "false"}
        >
          {/* Keyed by range so a tab switch re-mounts the cells and the wipe
              replays — the whole cost is the render the switch already does.
              Pinning a cell rewrites ?date only, leaving the key alone, so a
              click never re-runs the sweep. */}
          <div
            className="tape__grid"
            key={range}
            onPointerLeave={() => setHover(null)}
          >
            {cells.map((c, i) => (
              <button
                key={c.date}
                type="button"
                aria-label={cellLabel(c.date, c.pct)}
                title={cellLabel(c.date, c.pct)}
                className={`tape__cell${
                  hatch && isDownCell(c.pct) ? " is-hatched" : ""
                }`}
                /* backgroundColor, not the `background` shorthand — the hatch
                   class layers a background-image on top of it. */
                style={
                  {
                    gridColumn: c.col,
                    gridRow: c.row,
                    backgroundColor: heatColor(c.pct),
                    boxShadow: i === pinnedIdx ? PIN_RING : undefined,
                    "--d": `${(i === pinnedIdx ? sweep.ringMs : i * sweep.stepMs).toFixed(1)}ms`,
                  } as React.CSSProperties
                }
                onPointerEnter={() => setHover(i)}
                onFocus={() => setHover(i)}
                onClick={() => handleCellClick(c.date)}
              />
            ))}
          </div>
        </div>
      )}

      <div className="tape__foot">
        <div className="tape__legend">
          <span className="tape__legend-neg">−2%</span>
          <span className="tape__legend-grad" aria-hidden />
          <span className="tape__legend-pos">+2%</span>

          {/* Shape-codes direction for viewers who cannot separate the red
              ramp from the ink ramp by value alone. The cells' aria-labels
              already spell out up/down, so this is a visual aid only — no
              aria-live, nothing announced on toggle beyond the pressed state
              of the control itself. */}
          <button
            type="button"
            className={`tape__hatch${hatch ? " is-on" : ""}`}
            aria-pressed={hatch}
            aria-describedby="tape-hatch-note"
            onClick={toggleHatch}
          >
            <span className="tape__hatch-box" aria-hidden />
            HATCH
          </button>
          <span className="tape__hatch-note" id="tape-hatch-note">
            Hatch marks down days
          </span>
        </div>
        <span className="tape__caption">
          One cell per trading day · weeks as columns · click to pin
        </span>
      </div>

      <style jsx>{`
        .tape {
          font-family: var(--ins-font);
          color: var(--ins-ink);
          font-variant-numeric: tabular-nums;
          border-top: 3px solid var(--ins-rule-strong);
          padding-top: 16px;
        }
        .tape__anchor {
          scroll-margin-top: 110px;
        }

        /* ── Head ───────────────────────────────────────────────── */
        .tape__head {
          display: flex;
          justify-content: space-between;
          align-items: baseline;
          gap: 20px;
        }
        /* TRUE LABEL — a section kicker, not a sentence. Stays caps; takes
           the 10px floor. Tracking held at 0.2em: the head is a free-width
           flex child (the tabs are the only fixed thing in the row) and
           "SESSIONS ON FILE" measures ~131px at 10px/0.2em, so nothing is
           being squeezed. */
        .tape__kicker {
          font-size: 10px;
          font-weight: 700;
          letter-spacing: 0.2em;
          text-transform: uppercase;
          color: var(--ins-signal);
        }
        .tape__display {
          margin: 8px 0 0;
          font-size: 28px;
          font-weight: 700;
          letter-spacing: -0.02em;
          line-height: 1.1;
        }
        .tape__tabs {
          display: flex;
          gap: 6px;
          flex-shrink: 0;
        }
        .tape__tab {
          appearance: none;
          background: none;
          border: 1px solid transparent;
          border-radius: 0;
          padding: 5px 11px;
          font-family: inherit;
          font-size: 10px;
          font-weight: 700;
          letter-spacing: 0.08em;
          color: var(--ins-gray-600);
          cursor: pointer;
        }
        .tape__tab:not(.is-active):hover {
          border-color: var(--ins-hair);
        }
        .tape__tab.is-active {
          background: var(--ins-ink);
          color: var(--ins-paper);
        }

        /* ── Facts strip ────────────────────────────────────────── */
        .tape__stats {
          display: grid;
          grid-template-columns: repeat(4, 1fr);
          margin-top: 14px;
          border-top: 1px solid var(--ins-hair);
          border-bottom: 1px solid var(--ins-hair);
        }
        .tape__stat {
          padding: 12px 0 12px 20px;
          border-left: 1px solid var(--ins-hair);
          min-width: 0;
        }
        .tape__stat:first-child {
          padding-left: 0;
          border-left: none;
        }
        /* TRUE LABELS — stat names ("Sessions", "Worst day"). Caps at the
           floor. Tracking kept at 0.18em: the longest head, "WORST DAY",
           measures ~72px at 10px/0.18em against a ~230px desktop cell and a
           ~165px mobile cell, so the fixed track has room to spare and there
           is nothing to dial back. */
        .tape__stat-label {
          font-size: 10px;
          font-weight: 600;
          letter-spacing: 0.18em;
          text-transform: uppercase;
          color: var(--ins-gray-600);
        }
        .tape__stat-value {
          margin-top: 4px;
          font-size: 22px;
          font-weight: 700;
          line-height: 1.1;
        }
        .tape__stat-value.is-signal {
          color: var(--ins-signal);
        }
        /* Still a LABEL, not a caption — "SINCE INCEPTION", "68% OF SESSIONS",
           a date. Short noun phrases with no verb, so they keep caps at the
           floor rather than becoming 12px sentence case. "SINCE INCEPTION"
           is the longest at ~108px, well inside the cell. */
        .tape__stat-sub {
          margin-top: 2px;
          font-size: 10px;
          font-weight: 600;
          letter-spacing: 0.1em;
          text-transform: uppercase;
          color: var(--ins-gray-600);
        }

        /* ── Readout ────────────────────────────────────────────── */
        .tape__readout {
          display: flex;
          justify-content: space-between;
          align-items: baseline;
          gap: 12px;
          margin-top: 14px;
          font-size: 10px;
          font-weight: 700;
          letter-spacing: 0.16em;
          text-transform: uppercase;
        }
        .tape__read-left {
          color: var(--ins-gray-600);
        }
        .tape__read-date {
          color: var(--ins-ink);
        }
        .tape__read-pct {
          color: var(--ins-ink);
        }
        .tape__read-pct.is-neg {
          color: var(--ins-signal);
        }

        /* ── Heat grid ──────────────────────────────────────────── */
        .tape__scroll {
          margin-top: 12px;
          overflow-x: auto;
          padding: 3px 3px 4px;
        }
        .tape__grid {
          display: grid;
          grid-template-rows: repeat(5, 16px);
          grid-auto-flow: column;
          grid-auto-columns: minmax(6px, 1fr);
          gap: 2px;
          min-width: 100%;
        }
        .tape__cell {
          appearance: none;
          border: none;
          padding: 0;
          border-radius: 2px;
          cursor: pointer;
        }
        .tape__cell:focus-visible {
          outline: 2px solid var(--ins-signal);
          outline-offset: 1px;
        }
        /* Hatch overlay — down days only, opt-in. 1px lines at 45° on a 4px
           period, in literal paper white at low opacity so it reads as
           texture on the red rather than as a second colour. Literal, not
           var(--ins-paper): the cells themselves are literal by spec and stay
           red under the ink edition, so the marks must stay white there too.
           Identical to the home card's rule. */
        .tape__cell.is-hatched {
          background-image: repeating-linear-gradient(
            45deg,
            rgba(255, 255, 255, 0.55) 0 1px,
            transparent 1px 4px
          );
        }
        /* The fill sweep. Declared ONLY under [data-armed], so the un-armed
           frame — no JS, reduced motion (globals kills animation on .ins-root
           outright), before the board is scrolled to — is the finished board.
           Fill mode "both" holds the cell invisible through its stagger delay;
           the delay itself is per-cell, set inline as --d. Transform and
           opacity only, so
           every cell composites. Literal 260ms rather than an interpolated
           constant: an interpolation would make this whole sheet dynamic, and
           the board re-renders on every hover. */
        .tape__scroll[data-armed="true"] .tape__cell {
          animation: ins-cellIn 260ms ease-out both;
          animation-delay: var(--d, 0ms);
        }
        @keyframes ins-cellIn {
          from {
            opacity: 0;
            transform: scale(0.55);
          }
          to {
            opacity: 1;
            transform: none;
          }
        }
        .tape__skeleton {
          height: 88px; /* 5 × 16px rows + 4 × 2px gaps */
          margin-top: 12px;
          background: rgba(17, 17, 17, 0.06);
          animation: ins-pulse 2.2s ease-in-out infinite;
        }

        /* ── Legend + caption ───────────────────────────────────── */
        .tape__foot {
          display: flex;
          justify-content: space-between;
          align-items: center;
          /* Wraps now: the row gained the hatch control and its note, and the
             caption went from 9px caps to 12px sentence case, so on a narrow
             desktop the two halves need somewhere to go. */
          flex-wrap: wrap;
          gap: 10px 16px;
          /* was 12px — the hatch control carries 17px of top padding of its
             own, so the row keeps its optical distance from the grid without
             stacking the two. */
          margin-top: 2px;
        }
        .tape__legend {
          display: flex;
          align-items: center;
          gap: 8px;
          /* End labels are TRUE LABELS ("−2%" / "+2%") — at the floor. */
          font-size: 10px;
          font-weight: 700;
        }
        .tape__legend-neg {
          color: var(--ins-signal);
        }
        .tape__legend-pos {
          color: var(--ins-ink);
        }
        /* Regenerated to read heatColor() (lib/instrument-format) out exactly,
           −2% → +2%:
             −2%  a 0.92 red   ·  −1%  a 0.71 red  ·  the 0.20 red floor
             0    the flat cell, rgba(17,17,17,0.05) over paper = #f3f3f3
             +1%  a 0.69 ink   ·  +2%  a 0.92 ink
           The hard stops either side of centre are not decoration — they are
           the floors, i.e. the step a cell takes the moment it stops being a
           flat day. The red step is the one the accessibility pass
           introduced, and this board was still drawing the pre-floor ramp
           (0.88 → 0.30 → #f2f2f2 → 0.30 → 0.88), which agreed with neither
           the old function nor the new one. Same literal as the home card. */
        .tape__legend-grad {
          width: 180px;
          height: 7px;
          border: 1px solid var(--ins-hair);
          background: linear-gradient(
            90deg,
            rgba(232, 68, 46, 0.92) 0%,
            rgba(232, 68, 46, 0.71) 25%,
            rgba(232, 68, 46, 0.2) 49%,
            #f3f3f3 49%,
            #f3f3f3 51%,
            rgba(17, 17, 17, 0.1) 51%,
            rgba(17, 17, 17, 0.69) 75%,
            rgba(17, 17, 17, 0.92) 100%
          );
        }

        /* ── Hatch toggle (Instrument checkbox grammar) ─────────── */
        /* The 44px target is padding: 11px box + 17px above and below = 45px
           tall, ~78px wide. The padding is left in flow rather than pulled
           back out with negative margins — a negative margin would put the
           tap area on top of the last row of heat cells, which are themselves
           clickable buttons, and let the toggle steal their taps. The foot's
           top margin is reduced to pay for the height instead. */
        .tape__hatch {
          appearance: none;
          background: none;
          border: 0;
          border-radius: 0;
          display: inline-flex;
          align-items: center;
          gap: 7px;
          padding: 17px 10px;
          margin: 0 0 0 4px;
          font-family: inherit;
          /* 10px floor rather than the home card's 8.5px; tracking dialled
             one notch to 0.12em so the five-letter word keeps the same
             optical width in the row. */
          font-size: 10px;
          font-weight: 700;
          letter-spacing: 0.12em;
          color: var(--ins-gray-600);
          cursor: pointer;
        }
        .tape__hatch.is-on {
          color: var(--ins-ink);
        }
        .tape__hatch:focus-visible {
          outline: 2px solid var(--ins-signal);
          outline-offset: 2px;
        }
        .tape__hatch-box {
          width: 11px;
          height: 11px;
          flex: none;
          border: 1.5px solid var(--ins-ink);
          background: var(--ins-paper);
        }
        /* The swatch prints the mark it switches on. */
        .tape__hatch.is-on .tape__hatch-box {
          background-color: var(--ins-ink);
          background-image: repeating-linear-gradient(
            45deg,
            rgba(255, 255, 255, 0.9) 0 1px,
            transparent 1px 3px
          );
        }
        /* EXPLANATORY CAPTION — it explains what the control does. */
        .tape__hatch-note {
          font-size: 12px;
          font-weight: 500;
          letter-spacing: 0;
          text-transform: none;
          color: var(--ins-gray-600);
          white-space: nowrap;
        }
        /* EXPLANATORY CAPTION — a fragment that explains how to read the
           board, not a name for anything. Out of 9px caps + 0.14em and into
           the caption role; the string was already authored in sentence case,
           so only the transform had to go. */
        .tape__caption {
          font-size: 12px;
          font-weight: 500;
          letter-spacing: 0.01em;
          color: var(--ins-gray-600);
          text-align: right;
        }

        /* ── Mobile 390 ─────────────────────────────────────────── */
        @media (max-width: 640px) {
          .tape {
            border-top-width: 2px;
            padding-top: 12px;
          }
          .tape__head {
            display: block;
          }
          /* Floor + one notch of tracking back (0.18em → 0.14em): the head
             is display:block here, so the kicker owns the full 358px line and
             "SESSIONS ON FILE" lands at ~122px. */
          .tape__kicker {
            font-size: 10px;
            letter-spacing: 0.14em;
          }
          .tape__display {
            margin-top: 6px;
            font-size: 24px;
          }
          .tape__tabs {
            margin-top: 10px;
          }
          /* Three tabs (90D / 1Y / ALL) share the row so each can carry a
             44px target without crowding the display line out of the head. */
          .tape__tab {
            flex: 1 1 0;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            min-height: 44px;
            padding: 4px 9px;
            font-size: 10px;
          }
          .tape__stats {
            grid-template-columns: 1fr 1fr;
            margin-top: 12px;
          }
          .tape__stat {
            padding: 10px 0 10px 14px;
          }
          .tape__stat:nth-child(odd) {
            padding-left: 0;
            border-left: none;
          }
          .tape__stat:nth-child(n + 3) {
            border-top: 1px solid var(--ins-hair);
          }
          .tape__stat-value {
            font-size: 18px;
          }
          .tape__stat-sub {
            font-size: 10px;
            letter-spacing: 0.08em;
          }
          /* Floor at 10px, tracking held at 0.12em: the row is
             space-between, and its two halves measure ~126px + ~59px inside
             a 358px line. */
          .tape__readout {
            margin-top: 12px;
            font-size: 10px;
            letter-spacing: 0.12em;
          }
          .tape__scroll {
            margin-top: 10px;
          }
          .tape__grid {
            grid-template-rows: repeat(5, 13px);
            grid-auto-columns: minmax(9px, 1fr);
          }
          .tape__skeleton {
            height: 73px; /* 5 × 13px rows + 4 × 2px gaps */
            margin-top: 10px;
          }
          .tape__foot {
            display: block;
            margin-top: 0;
          }
          /* The legend row survives on mobile for one reason — the hatch
             toggle is the direction affordance and must not be desktop-only.
             Its neighbours (the gradient and the ±2% end labels) drop out;
             the toggle and its note stay. Same call the home card makes. */
          .tape__legend-neg,
          .tape__legend-pos,
          .tape__legend-grad {
            display: none;
          }
          .tape__hatch {
            margin-left: 0;
            padding-left: 0;
          }
          .tape__caption {
            text-align: left;
          }
        }
      `}</style>
    </section>
  );
}
